[package]
name = "gamesavesync"
description = "A tool for synchronizing game saves across devices"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
